service: serverlessclojure
frameworkVersion: '2'

provider:
  name: aws
  runtime: java11
  region: us-east-2
  timeout: 10
  memorySize: 1024
  lambdaHashingVersion: 20201221

package:
  artifact: target/calcstandalone.jar

functions:
  simpleLambda:
    handler: calc.core.ApiHandler
  simpleHttp:
    handler: calc.core.ApiHandler
    events:
      - httpApi:
          method: POST
          path: /dev/calc
